version: '3.9'

services:
  bot:
    container_name: 'lisa-discord-bot-${STAGING}'
    build: ./bot
    restart: always
    env_file: .env
    depends_on:
      - 'db'
    environment:
      - DB_FORCE=${DB_FORCE}

  rater:
    container_name: 'lisa-discord-rater-${STAGING}'
    build: ./rater
    restart: always
    env_file: .env

  db:
    container_name: 'lisa-discord-postgresql-${STAGING}'
    build: ./db
    restart: always
    env_file: .env
    ports:
      - '9302:5432'
    volumes:
      - '/opt/lisa-discord/${STAGING}/postgres/:/var/lib/postgresql/data/'

  postgres-exporter:
    container_name: 'lisa-discord-postgres-exporter-${STAGING}'
    image: quay.io/prometheuscommunity/postgres-exporter
    restart: always
    env_file: .env
    ports:
      - '${POSTGRES_EXPORTER_HOST}:${POSTGRES_EXPORTER_PORT}:9187'
    profiles: ['prod']
    depends_on:
      - db
