version: '3.9'

services:
  bot:
    container_name: 'lisa-discord-bot-${STAGING}'
    build: ./bot
    image: ams.ocir.io/ax4e0xrv7kjj/lisa/bot:${TAG-latest}
    restart: always
    env_file: .env
    networks:
      - default
      - nginx-proxy
    volumes:
      - './.env:/app/.env'
    environment:
      - DB_FORCE=${DB_FORCE}
      - VIRTUAL_HOST=${API_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${API_HOST_LE}
    depends_on:
      - 'db'
      - 'redis'

  rater:
    container_name: 'lisa-discord-rater-${STAGING}'
    build: ./rater
    image: ams.ocir.io/ax4e0xrv7kjj/lisa/rater:${TAG-latest}
    restart: always
    env_file: .env
    volumes:
      - './.env:/app/.env'

  db:
    container_name: 'lisa-discord-postgresql-${STAGING}'
    build: ./db
    image: ams.ocir.io/ax4e0xrv7kjj/lisa/db:${TAG-latest}
    restart: always
    env_file: .env
    ports:
      - '9302:5432'
    volumes:
      - '${DATA_MOUNT_PATH}/${STAGING}/postgres/:/var/lib/postgresql/data/'

  redis:
    container_name: 'lisa-discord-redis-${STAGING}'
    build: ./redis
    image: ams.ocir.io/ax4e0xrv7kjj/lisa/redis:${TAG-latest}
    restart: always
    env_file: .env
    ports:
      - '19343:6379'
    volumes:
      - '${DATA_MOUNT_PATH}/${STAGING}/redis/:/data'

  postgres-exporter:
    container_name: 'lisa-discord-postgres-exporter-${STAGING}'
    build: ./devops/postgres-exporter
    image: ams.ocir.io/ax4e0xrv7kjj/lisa/postgres-exporter:${TAG-latest}
    restart: always
    env_file: .env
    profiles: ['monitor']
    ports:
      - '19187:9187'
    depends_on:
      - db

  ghost:
    container_name: 'lisa-discord-ghost-${STAGING}'
    build: ./ghost
    image: ams.ocir.io/ax4e0xrv7kjj/lisa/ghost:${TAG-latest}
    restart: always
    env_file: .env
    profiles: ['site']
    networks:
      - default
      - nginx-proxy
    volumes:
      - '${DATA_MOUNT_PATH}/${STAGING}/ghost-content/:/var/lib/ghost/content'
    environment:
      - VIRTUAL_HOST=${GHOST_HOST}
      - LETSENCRYPT_HOST=${GHOST_HOST_LE}
      - url=${GHOST_URL}
      - paths__contentPath=custom
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=root
      - database__connection__password=${MYSQL_ROOT_PASSWORD}
      - database__connection__database=ghost
      - mail__transport=SMTP
      - mail__from=${GHOST_MAIL_FROM}
      - mail__options__host=${GHOST_MAIL_HOST}
      - mail__options__port=465
      - mail__options__secureConnection=true
      - mail__options__maxConnections=1
      - mail__options__auth__user=${GHOST_MAIL_USER}
      - mail__options__auth__pass=${GHOST_MAIL_PASS}
    depends_on:
      - ghost-db

  ghost-db:
    container_name: 'lisa-discord-mariadb-${STAGING}'
    image: mariadb:10.6.4
    restart: always
    env_file: .env
    profiles: ['site']
    ports:
      - '9303:3306'
    volumes:
      - '${DATA_MOUNT_PATH}/${STAGING}/ghost-db/:/var/lib/mysql'

  admin:
    container_name: 'lisa-discord-admin-${STAGING}'
    build:
      context: ./admin
      args:
        REACT_APP_API_HOST: ${API_HOST}
        REACT_APP_API_HOST_LE: ${API_HOST_LE}
    image: ams.ocir.io/ax4e0xrv7kjj/lisa/admin:${TAG-latest}
    restart: always
    env_file: .env
    profiles: ['admin']
    networks:
      - default
      - nginx-proxy
    volumes:
      - './admin/test/screenshots:/app/test/screenshots'
    environment:
      - VIRTUAL_HOST=${ADMIN_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${ADMIN_HOST_LE}
    depends_on:
      - 'bot'

networks:
  default:
    name: lisa-discord-bot
  nginx-proxy:
    name: nginx-proxy
    external: true
