version: '3.9'

services:
  bot:
    container_name: 'lisa-discord-bot-${STAGING}'
    build: ./bot
    restart: always
    env_file: .env
    depends_on:
      - 'db'
    environment:
      - DB_FORCE=${DB_FORCE}

  rater:
    container_name: 'lisa-discord-rater-${STAGING}'
    build: ./rater
    restart: always
    env_file: .env
    volumes:
      - "/opt/lisa-discord/${STAGING}/rater:/data/"

  db:
    container_name: 'lisa-discord-postgresql-${STAGING}'
    image: postgres:13-alpine
    restart: always
    env_file: .env
    ports:
      - '9302:5432'
    volumes:
      - "/opt/lisa-discord/${STAGING}/postgres/:/var/lib/postgresql/data/"

